-- DNS查询记录表
CREATE TABLE IF NOT EXISTS dns_query_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(255) NOT NULL,
    query_type VARCHAR(10) NOT NULL,
    response_ip VARCHAR(50),
    cache_hit BOOLEAN DEFAULT FALSE,
    query_time TIMESTAMP NOT NULL,
    response_time_ms INTEGER
);

CREATE INDEX IF NOT EXISTS idx_domain ON dns_query_records(domain);
CREATE INDEX IF NOT EXISTS idx_query_time ON dns_query_records(query_time);

-- 插入一些测试数据
INSERT INTO dns_query_records (domain, query_type, response_ip, cache_hit, query_time, response_time_ms)
VALUES
    ('example.com', 'A', '93.184.216.34', false, CURRENT_TIMESTAMP, 45),
    ('google.com', 'A', '142.250.185.46', false, CURRENT_TIMESTAMP, 32),
    ('github.com', 'A', '140.82.121.4', true, CURRENT_TIMESTAMP, 5);
